### ISSUE TITLE
Question about 3D Visualization

### ISSUE THREAD

**Issue by Boey-li** [henry123-boy/SpaTracker#31]
Hello, thanks for the amazing work!  I have similar questions with the #13 , where I can not reproduce the 3D visualization using the `sintel_bandage_3d.npy` and the blender script. I have met the issue
```
 File "/Users/baoyu/research/visualizer/create.py", line 62, in <module>
    obj = bpy.data.objects[basename]
KeyError: 'bpy_prop_collection[key]: key "assets/sintel_bandage_3d_2" not found'
```
Do you have any sense for such bug? 

And I also tried to visualize the 3D tracking performance using `Open3D` and `sintel_bandage_spatracker_tracks.npy` but the results are not good as you showed in the website. Can you also provide the 3D visualization code using Open3D if possible? 

Thanks!

**Comment by mgladkova** [comment]
Hello!

I also faced a similar issue and, after investigating the keys of `bpy.data.objects` dict, the solution was to extract the filename's stem:
`
obj = bpy.data.objects[basename[basename.rfind('/')+1:]]
`
Hope it helps!

**Comment by 52THANOS** [comment]
> Hello! 你好！
> 
> I also faced a similar issue and, after investigating the keys of `bpy.data.objects` dict, the solution was to extract the filename's stem:我也遇到了类似的问题，在调查了 `bpy.data.objects` dict 的键后，解决方案是提取文件名的词干： `obj = bpy.data.objects[basename[basename.rfind('/')+1:]]` Hope it helps! 希望它有帮助！

i have some issues with 3d visualization.  i wonder what bpy version did you use 
![1727148427783](https://github.com/user-attachments/assets/35427ccc-490c-4eb1-87f4-efd798e18a40)

**Comment by mgladkova** [comment]
I am using the latest blender version 4.2.1 and launch the command as described in readme:

**Comment by 52THANOS** [comment]
> I use the latest blender version 4.2.1 and launch the command as described in [readme](https://github.com/henry123-boy/SpaTracker?tab=readme-ov-file#visualization-3d-trajectories).我使用最新的 blender 版本 4.2.1 并按照[自述文件](https://github.com/henry123-boy/SpaTracker?tab=readme-ov-file#visualization-3d-trajectories)中所述启动命令。

shoot! i rewrote some of the scripts to make it run.  did you use the bpy or the scripting in blender4.2

**Comment by g8392** [comment]
I am having error in 4.2.1:

  File "/media/ed/FSSD/DATA/GITHUB/SpaTracker/blender_vis/create.py", line 38, in <module>
    rgb = data[:,:,[3,4,5]]
          ~~~~^^^^^^^^^^^^^
IndexError: index 3 is out of bounds for axis 2 with size 3

Blender quit

**Comment by ppuskas** [comment]
> I am having error in 4.2.1:
> 
> File "/media/ed/FSSD/DATA/GITHUB/SpaTracker/blender_vis/create.py", line 38, in rgb = data[:,:,[3,4,5]] ~~~~^^^^^^^^^^^^^ IndexError: index 3 is out of bounds for axis 2 with size 3
> 
> Blender quit

I am also getting something similar with 

IndexError: index 7 is out of bounds for axis 0 with size 7

**Comment by qinghew** [comment]
> > I am having error in 4.2.1:
> > File "/media/ed/FSSD/DATA/GITHUB/SpaTracker/blender_vis/create.py", line 38, in rgb = data[:,:,[3,4,5]] ~~~~^^^^^^^^^^^^^ IndexError: index 3 is out of bounds for axis 2 with size 3
> > Blender quit
> 
> I am also getting something similar with
> 
> IndexError: index 7 is out of bounds for axis 0 with size 7

use another saved npy

**Comment by qinghew** [comment]
if the input is relative path, **basename = args.input.split('.')[0]** will split the first "." in "./vis_blender..." out. And basename will equal " ".

**Comment by qinghew** [comment]
my blender version is 4.2.1
refer:
1. https://github.com/henry123-boy/SpaTracker/issues/13#issuecomment-2202262486
2. https://github.com/henry123-boy/SpaTracker/issues/31#issuecomment-2363151025

when edit the code "basename = basename.split('\\')[-1]", it is related to your path. 
for example, my path is "/user/xxx/data_process/vis_blender/vis_results/s023_04061_3d.npy", the code should be :
  basename = basename.split('/')[-1]
  
3. if you meet the error:
Traceback (most recent call last):
  File "/Users/qinghewang/Documents/codes/data_process/vis_blender/create.py", line 79, in <module>
    group_input = node_tree.nodes['Group Input']
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Group Input" not found'

change the language to English
